### ISSUE TITLE
깃 로그에 서버 주소가 여전히 남아있습니다.

### ISSUE THREAD

**Issue by shyuuuuni** [qsc7342/BanchanMangement#1]
commit [67c332c](https://github.com/qsc7342/BanchanMangement/commit/67c332cf69c653e65a1744d2d4911a9d6bc4f651)

깃 커밋 내역을 보면 이전 서버 주소가 여전히 보이는 문제가 있어보입니다.

보안상 커밋 내역을 아예 없애서 완전히 가리시는게 더 좋아보여요.

**Comment by qsc7342** [comment]
개발 전용 서버로 보안 상 큰 문제 없습니다.
